target 'InstagramKit-Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!

pod 'InstagramKit', :git => 'https://github.com/dee-lewis/InstagramKit.git'
pod 'InstagramKit/UICKeyChainStore', :git => 'https://github.com/dee-lewis/InstagramKit.git'

end
