target 'InstagramKit-Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!

  pod 'InstagramKit', '~> 3.0'
  pod 'InstagramKit/UICKeyChainStore'

end
